// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ksmninebkiqxcrhnumps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbW5pbmVia2lxeGNyaG51bXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4ODkyMDMsImV4cCI6MjA4MzQ2NTIwM30.jrywRypE7xYOGU7EdvQiUB9XjY2Kw7-GyJ2rVjteUNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);